---

# yamllint disable rule:line-length
specfile_path: ../distro/stratis-cli.spec
merge_pr_in_ci: false

downstream_package_name: stratis-cli

actions:
  post-upstream-clone:
    - "mkdir ../distro"
    - "wget https://raw.githubusercontent.com/stratis-storage/ci/master/mockbuild_test/stratis-cli.spec -O ../distro/stratis-cli.spec"
    - "wget https://raw.githubusercontent.com/stratis-storage/ci/master/release_management/create_artifacts.py -O ../distro/create_artifacts.py"
    - "wget https://raw.githubusercontent.com/stratis-storage/ci/master/release_management/_utils.py -O ../distro/_utils.py"
  create-archive:
    - "sh -c 'python3 ../distro/create_artifacts.py ../distro/ stratis-cli $(rpmspec -q --srpm --qf %{Version} ../distro/stratis-cli.spec)'"
    - "sh -c 'echo ../distro/stratis-cli-$(rpmspec -q --srpm --qf %{Version} ../distro/stratis-cli.spec).tar.gz'"
  get-current-version:
    - "python3 setup.py --version"

srpm_build_deps:
  - python3-pip
  - wget

jobs:
  - job: copr_build
    trigger: pull_request
    manual_trigger: true
    targets:
      - fedora-stable
