os: linux
dist: xenial
language: python
python: "3.5" # dbus-python can not be built on higher versions of Python

addons:
  apt:
    packages:
      libdbus-glib-1-dev

branches:
    only: master

matrix:
    - TASK=lint
    - TASK=fmt-travis

script: make -f Makefile $TASK
